### ISSUE TITLE
icon refreshed

### ISSUE THREAD

**Issue by Greenbaburu** [mancuniancol/script.quasar.nyaa-mc#1]
I really hope that not offend you
 
![nyaa](https://cloud.githubusercontent.com/assets/8045152/13461689/627b6ee0-e083-11e5-921e-a91d076290f4.jpg)
![nyaa](https://cloud.githubusercontent.com/assets/8045152/13461693/6630fe10-e083-11e5-92c3-337e11f3e345.png)

**Comment by Greenbaburu** [comment]
I mean, the icon is the same. Just more clean

**Comment by mancuniancol** [comment]
It looks much better. Thanks
