### ISSUE TITLE
does not work on quasar 9.3.3

### ISSUE THREAD

**Issue by lovepupils** [mancuniancol/script.quasar.nyaa-mc#2]
Hello I am using the Nyaa Provider 1.3.5 on latest Quasar 9.3.3 for Android Arm (Nvidia Shield TV) on Kodi 16.1.

Every other provider I tried works just fine, but nyaa always shows zero results.
I tried looking in the configuration but everything looks fine.

Let me know if I can help you with logs etc. and where to take them.
Thanks

**Comment by mancuniancol** [comment]
I will check it. If I can't reproduce the issue. I will ask you your log. Thank you for your feedback

**Comment by mancuniancol** [comment]
I've done adjustment.  Could you try it for me?

https://github.com/mancuniancol/script.quasar.nyaa-mc/archive/v1.3.6.zip

**Comment by lovepupils** [comment]
thank you, I will be able to give you a feedback in 5 hours or so.

**Comment by lovepupils** [comment]
I'm back from testing.
It mostly works now, thank you.
By mostly I mean it only seems to show me "trusted" torrents (the ones in green or white on the site),
I can't seem to have it show the untrusted/remakes ones (in red), which I like for certain subgroups.
I also tried to put the same url I use on my pc, to no avail:
http://www.nyaa.se/?page=search&cats=1_37&filter=0

Thank you for your fast work by the way!

**Comment by mancuniancol** [comment]
Well, you can edit the main.py to adjust to your requirements. 
You open it with notepad and search all:

"%s/?page=search&cats=1_0&term=%s&sort=2"
I think you need to change the category. 
%s/?page=search&cats=1_37&term=%s&sort=2
